title: "HFES Western Student Chapter"
description: "Human Factors and Ergonomics Society at Western University"
baseurl: "/HFES-Western"
url: "https://hfes-western.github.io"
locale: "en-CA"

# No theme, no remote_theme, no plugins for themes

plugins:
  - jekyll-feed          # optional, generates RSS feed
  - jekyll-seo-tag       # optional, adds meta tags for SEO

collections:
  pages:
    output: true
    permalink: /:name/